# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ef4a185769da4353b74a94066c6cea5e57f7e19685045609adebddb8f59b435ddbf3ad8045623f1e91e36cba1b9d93d22aad9ddf82ffdf81754909499120090

test:
  secret_key_base: e0e34c6bcf1c908a6ae3a365ac63e838f684abce765f73b42bbf15bffaa53d29e776afe531ed6c589b223ec11a4c2b12a24a9e76dc128d27d9625f5bedd4b977

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
